- Formula/aks-engine.rb
I tested this from my local master branch by doing `brew install mboersma/aks-engine/aks-engine`.
> feat: add aks-engine release v0.31.2

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.31.3
Tested by pushing to my fork's master and doing "brew install mboersma/aks-engine/aks-engine."
> feat: add aks-engine release v0.31.3

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.32.0
Tested by pushing to my fork's master and doing "brew install mboersma/aks-engine/aks-engine."
> feat: add aks-engine release v0.32.0

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.32.1
Tested by pushing to my fork's master and doing "brew install mboersma/aks-engine/aks-engine."
> feat: add aks-engine release v0.32.1

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.32.3
Tested by pushing to my fork's master and doing `brew install mboersma/aks-engine/aks-engine`.
> feat: add aks-engine release v0.32.3

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.33.1
> feat: add aks-engine release v0.33.1

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.33.2
> feat: add aks-engine release v0.33.2

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.33.4
> feat: add aks-engine release v0.33.4

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.33.5
> feat: add aks-engine release v0.33.5

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.34.0
> feat: add aks-engine release v0.34.0

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.34.1
> feat: add aks-engine release v0.34.1

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.35.0
> feat: add aks-engine release v0.35.0

- Formula/aks-engine.rb
https://github.com/Azure/aks-engine/releases/tag/v0.35.1
> feat: add aks-engine release v0.35.1

- Formula/aks-engine.rb
https://github.com/Azure/aks-engine/releases/tag/v0.36.0
> feat: add aks-engine release v0.36.0

- Formula/aks-engine.rb
https://github.com/Azure/aks-engine/releases/tag/v0.36.1
> feat: add aks-engine release v0.36.1

- Formula/aks-engine.rb
https://github.com/Azure/aks-engine/releases/tag/v0.36.2
> feat: add aks-engine release v0.36.2

- Formula/aks-engine.rb
https://github.com/Azure/aks-engine/releases/tag/v0.36.3
> feat: add aks-engine release v0.36.3

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.36.4
> feat: add aks-engine release v0.36.4

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.36.5
> feat: add aks-engine release v0.36.5

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.37.0
> feat: add aks-engine release v0.37.0

- Formula/aks-engine.rb
https://github.com/Azure/aks-engine/releases/tag/v0.37.1
> feat: add aks-engine release v0.37.1

- Formula/aks-engine.rb
See:
https://github.com/Azure/aks-engine/releases/tag/v0.37.2
> chore: update to aks-engine v0.37.2

- Formula/aks-engine.rb
See:
https://github.com/Azure/aks-engine/releases/tag/v0.37.4
> chore: update to aks-engine v0.37.4

- Formula/aks-engine.rb
https://github.com/Azure/aks-engine/releases/tag/v0.38.0
> feat: add aks-engine release v0.38.0

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.38.1
> feat: add aks-engine release v0.38.1

- Formula/aks-engine.rb
https://github.com/Azure/aks-engine/releases/tag/v0.38.3
> feat: add aks-engine release v0.38.3

- Formula/aks-engine.rb
Add aks-engine v0.38.4
See:
https://github.com/Azure/aks-engine/releases/tag/v0.38.4
> chore: rev to v0.38.4

- Formula/aks-engine.rb
See:
https://github.com/Azure/aks-engine/releases/tag/v0.38.5
> chore: rev aks-engine to v0.38.5

- Formula/aks-engine.rb
See:
https://github.com/Azure/aks-engine/releases/tag/v0.39.0
> chore: update aks-engine to v0.39.0

- Formula/aks-engine.rb
See:
https://github.com/Azure/aks-engine/releases/tag/v0.39.1
> chore: v0.39.1

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.39.2
> chore: update aks-engine to v0.39.2

- Formula/aks-engine.rb
See:
https://github.com/Azure/aks-engine/releases/tag/v0.41.0
> chore: rev aks-engine to v0.41.0

- Formula/aks-engine.rb
Ref: https://github.com/Azure/homebrew-aks-engine/issues/36
> chore: rev aks-engine to v0.41.2

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.42.0
> chore: update aks-engine to v0.42.0

- Formula/aks-engine.rb
Ref:
https://github.com/Azure/aks-engine/releases/tag/v0.42.2
> chore: update to v0.42.2

- Formula/aks-engine.rb
Ref:
https://github.com/Azure/aks-engine/releases/tag/v0.44.0
> chore: rev aks-engine to v0.44.0

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.44.2
> chore: rev aks-engine to v0.44.2

- Formula/aks-engine.rb
See:
https://github.com/Azure/aks-engine/releases/tag/v0.45.0
> chore: update to v0.45.0

- Formula/aks-engine.rb
We should really figure out a way to sign these binaries so catalina can actually execute it. :/
> chore: rev to v0.46.1

- Formula/aks-engine.rb
See:
https://github.com/Azure/aks-engine/releases/tag/v0.46.2
> chore: rev to v0.46.2

- Formula/aks-engine.rb
See:
https://github.com/Azure/aks-engine/releases/tag/v0.47.0
> chore: rev aks-engine to v0.47.0

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.48.0
> chore: rev aks-engine to v0.48.0

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.49.0
> chore: rev aks-engine to v0.49.0

- Formula/aks-engine.rb
See:
https://github.com/Azure/aks-engine/releases/tag/v0.50.0
> chore: rev to v0.50.0

- Formula/aks-engine.rb
see: https://github.com/Azure/aks-engine/releases/tag/v0.50.2
> chore: v0.50.2

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.51.0
> chore: rev aks-engine to v0.51.0

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.52.0
> chore: rev aks-engine to v0.52.0

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.53.0
> chore: rev aks-engine to v0.53.0

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.54.0
> chore: rev aks-engine to v0.54.0

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.54.1
> chore: rev aks-engine to v0.54.1

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.55.1
> chore: rev aks-engine to v0.55.1

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.55.2
> chore: rev aks-engine to v0.55.2

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.55.3
> chore: rev aks-engine to v0.55.3

- Formula/aks-engine.rb
See https://github.com/Azure/aks-engine/releases/tag/v0.56.0
> chore: rev aks-engine to v0.56.0

- Formula/aks-engine.rb
Ref: https://github.com/Azure/aks-engine/releases/tag/v0.57.0
> chore: rev to v0.57.0

- Formula/aks-engine.rb
https://github.com/Azure/aks-engine/releases/tag/v0.58.0
> chore: rev to v0.58.0

- Formula/aks-engine.rb
https://github.com/Azure/aks-engine/releases/tag/v0.70.1
> chore: rev aks-engine to v0.70.1
